"""add_user_timezone_field

Revision ID: 4cde38d7f66c
Revises: 008
Create Date: 2025-08-19 12:13:38.927768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde38d7f66c'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_profile_stripe_account_id'))
        batch_op.create_unique_constraint('uq_coach_profile_stripe_account_id', ['stripe_account_id'])
        batch_op.drop_column('stripe_account_status')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('payment_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_contract_coach_id'))
        batch_op.drop_index(batch_op.f('ix_contract_contract_number'))
        batch_op.drop_index(batch_op.f('ix_contract_payment_status'))
        batch_op.drop_index(batch_op.f('ix_contract_status'))
        batch_op.drop_index(batch_op.f('ix_contract_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_contract_student_id'))
        batch_op.create_unique_constraint('uq_contract_contract_number', ['contract_number'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('accepted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('scheduled_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('reschedule_deadline',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('video_started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('video_ended_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('session_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('paid_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_session_payment_contract_id'))
        batch_op.drop_index(batch_op.f('ix_session_payment_status'))
        batch_op.drop_column('transfer_date')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('verification_doc')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.alter_column('new_email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('email_change_token_created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_user_stripe_customer_id'))
        batch_op.create_unique_constraint('uq_user_stripe_customer_id', ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_stripe_customer_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_stripe_customer_id'), ['stripe_customer_id'], unique=1)
        batch_op.alter_column('email_change_token_created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('new_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('timezone')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_doc', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('session_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_date', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('ix_session_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_payment_contract_id'), ['contract_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('paid_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('video_ended_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('video_started_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('reschedule_deadline',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.alter_column('accepted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contract_contract_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_contract_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_contract_number'), ['contract_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_coach_id'), ['coach_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('coach_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_status', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_coach_profile_stripe_account_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_coach_profile_stripe_account_id'), ['stripe_account_id'], unique=1)

    # ### end Alembic commands ### 